### Week-3 Assignment Solution: NumPy Basics

1. Introduction to NumPy and Array Creation (10 Marks)
- Create a 1D NumPy array with the elements [10, 20, 30, 40, 50]. (2 Marks)
- Create a 2D array of shape (2, 3) using numpy.zeros. (3 Marks)
- Use numpy.linspace to create an array of 5 evenly spaced numbers between 0 and 100. (5 Marks)


In [23]:
import numpy as np
one_D_array= np.array([10,20,30,40,50])
print("1D array:",one_D_array)
two_d=np.zeros((2,3))
print("2D array:",two_d)
a=np.linspace(0,100,5)
print("Linspaced array:",a)


1D array: [10 20 30 40 50]
2D array: [[0. 0. 0.]
 [0. 0. 0.]]
Linspaced array: [  0.  25.  50.  75. 100.]


2. Array Indexing and Slicing (10 Marks):
- Using the 1D array [5, 10, 15, 20, 25, 30]:
   - Extract the first 3 elements. (2 Marks)
   - Extract every second element. (3 Marks)
   - Change the 4th element to 50 and print the updated array. (5 Marks)


In [22]:
import numpy as np
given=np.array([5,10,15,20,25,30])
first_three=given[:3]
print("First 3 elements:",first_three)
every_second=given[::2]
print("Every second element:",every_second)

given[3]=50
new_array=given
print("Updated array:",new_array)

First 3 elements: [ 5 10 15]
Every second element: [ 5 15 25]
Updated array: [ 5 10 15 50 25 30]


3. Reshaping Arrays (10 Marks)
- Create a 1D array with 12 elements ranging from 1 to 12 using numpy.arange. (5 Marks)
- Reshape it into a 2D array of shape (3, 4). (5 Marks)


In [28]:
import numpy as np
array=np.arange(1,13)

print("Array with elements 1 to 12:",array)

new_a= array.reshape(3,4)
print("Reshaped array:",new_a)

Array with elements 1 to 12: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4. Broadcasting and Element-wise Operations (10 Marks)
- Create a 1D array with elements [1, 2, 3, 4, 5].
- Perform the following operations:
  - Add 10 to each element. (2 Marks)
  - Multiply each element by 3. (3 Marks)
  - Calculate the square of each element. (5 Marks)


In [31]:
import numpy as np
given=np.arange(1,6)
added_a=given +10
multiple_a=given*3
square_a=given**2
print("Given array:", given)
print("10 added array:" ,added_a)
print("Multiplied by 3 array:",multiple_a)
print("Squared array:",square_a)

Given array: [1 2 3 4 5]
10 added array: [11 12 13 14 15]
Multiplied by 3 array: [ 3  6  9 12 15]
Squared array: [ 1  4  9 16 25]


5. Basic Statistics with Arrays (10 Marks)
- Create a NumPy array representing daily temperatures for a week: [30, 32, 31, 29, 28, 33, 34].
  - Find the mean temperature of the week. (3 Marks)
  - Find the minimum and maximum temperatures. (3 Marks)
  - Calculate the total sum of the temperatures. (4 Marks)


In [36]:
import numpy as np
temp=np.array([30,32,31,29,28,33,34])

print("Given temperatures:",temp)
print("Mean temperature:",np.mean(temp))
print("Maximum temperature:",np.max(temp))
print("Mininum temperature:",np.min(temp))
print("Summation of temperatures:",np.sum(temp))

Given temperatures: [30 32 31 29 28 33 34]
Mean temperature: 31.0
Maximum temperature: 34
Mininum temperature: 28
Summation of temperatures: 217


6. Real-World Problem: Sales Analysis (10 Marks)

  1.Create a 2D array representing sales data for 2 products over 5 days:

less

Copy code

Product 1: [200, 220, 250, 270, 300]  
Product 2: [150, 160, 170, 180, 200]  


  - Calculate the total sales for each product. (4 Marks)
  - Calculate the average sales per day. (3 Marks)
  - Find the day with the highest sales for each product. (3 Marks)


In [67]:
import numpy as np
Product_1=np.array ([200, 220, 250, 270, 300])
Product_2= np.array([150, 160, 170, 180, 200])
products = np.array([Product_1,Product_2])
print("The combined 2D array:",products)
total_sales_product_1=np.sum(products[0])
print("Total sales for product 1 :",total_sales_product_1)
total_sales_product_2=np.sum(products[1])
print("Total sales for product 2 :",total_sales_product_2)
total_sales= np.sum(products)
avg_sales = total_sales/ len(products[0])
print ("The average sales per day :",avg_sales)
max_sales_day_for_product_1=np.argmax(products[0])
print("Highest sales day for product 1 is : Day",max_sales_day_for_product_1+1)
max_sales_day_for_product_2=np.argmax(products[1])
print("Highest sales day for product 2 is : Day",max_sales_day_for_product_1+1)




The combined 2D array: [[200 220 250 270 300]
 [150 160 170 180 200]]
Total sales for product 1 : 1240
Total sales for product 2 : 860
The average sales per day : 420.0
Highest sales day for product 1 is : Day 5
Highest sales day for product 2 is : Day 5
